In [19]:
import pandas as pd
pd.set_option('display.max_rows', None)

In [20]:
df = pd.read_csv("data/event_log_anonymized.csv").sort_values("Case_id")

In [21]:
df["Recruiting Agency"].value_counts()

Recruiting Agency
Spencer Ogden (US) (10052768)                              4751
LVI Associates (10140833)                                  4628
Singular Agency                                             966
The Sustainable Partnership (TSP) (10146025)                902
Talisman (10165145)                                         886
VACO Resources (10175478)                                   771
RO Energy (10144364) (Inactive)                             753
Futura Energy Group                                         737
Piper Maddox (10094162)                                     705
Dynamis (10160777)                                          668
Mirador Search Partners                                     489
Michael Page (US) (10169699)                                452
Andrews & Cole (10010210)                                   424
ROBERT HALF (USA - DC) (Inactive)                           370
Ripple Effect Consulting (10169695)                         306
Alakai Agency                                               289
Platinum Recruiting Group                                   281
Bradsby group (Inactive)                                    264
Insight Global, LLC                                         247
ERSG (Inactive)                                             223
CONSULT ENERGY (Inactive)                                   166
NextWave Partners USA INC (10174027)                        154
JD ROSS (Inactive)                                          144
Amica Talent LLC (Inactive)                                 143
Bloomfield Co. (Inactive)                                   140
Alliance (Inactive)                                         132
AI Ventures Management LLC                                  108
SELBY JENNINGS (10140833)                                   107
Concilium Search LLC (Inactive)                              98
EJ Norris Holdings LLC dba Norrco (Inactive)                 93
H-S International (Inactive)                                 93
Variant Partners (Inactive)                                  81
Primary Recruiting Services, LLC (10070324)                  80
The Alliance Group                                           76
Optimus (10181398)                                           71
Lumicity (10179642)                                          63
Peak Demand (Inactive)                                       62
Aerotek (US) (Inactive)                                      61
Jobot (Inactive)                                             56
Barker Gilmore LLC (Inactive)                                55
LHH Recruitment Solutions                                    54
Stanton Chase México                                         53
Frederick Fox (Inactive)                                     52
SaltHill Group (Inactive)                                    48
Next-Wave (Inactive)                                         45
ROBERT HALF (USA - CO)                                       42
Global Recruiters of Ellizabeth City (Inactive)              36
Randstad (Inactive)                                          32
Medallion Partners (Inactive)                                28
The Data Incubator                                           28
Bavana Partners (Inactive)                                   26
Hector and Streak Consulting Private Limited (Inactive)      24
RWR (Inactive)                                               24
Green Recruitment Company (Inactive)                         24
Encore Technologies (Inactive)                               22
Airboticstalent                                              21
PRePintl (Inactive)                                          20
APS (Inactive)                                               19
Actalent                                                     16
Bridgeway Search Group, Inc. (Inactive)                      14
Experis US LLC                                               12
Pangea Resourcing (Inactive)                                 11
Parker & Lynch (Inactive)                                    10
X4 Group (10192454)                                           8
Taylor Hopkinson (Inactive)                                   8
Dylan Green (Inactive)                                        4
ABC Consultants Private Limited                               4
Name: count, dtype: int64

In [22]:
df.head()

,Recruiting Agency,Region,Country,Job Family,Job Family Group,All Stages for Candidate Current and Completed,Disposition Reason,Step,Event Record,Completed On,Completed By,CW,Evergreen,Rejected,hired,Job_Requisition_Code,Case_id
805947,NaN,4,15,57,16,Declined by Candidate\n\nInterview\n\nStart,Candidate Withdrew,Schedule Interview,Schedule Interview,2024-10-17T15:22:10.434,6746,0,0,0,0,10fb9be7d6ea,000086ee80c8 - 10fb9be7d6ea
805956,NaN,4,15,57,16,Declined by Candidate\n\nInterview\n\nStart,Candidate Withdrew,Make Interview Decision,Make Interview Decision,2024-11-04T15:21:58.288,6746,0,0,0,0,10fb9be7d6ea,000086ee80c8 - 10fb9be7d6ea
805955,NaN,4,15,57,16,Declined by Candidate\n\nInterview\n\nStart,Candidate Withdrew,Manager Interview,Manager Interview,2024-11-04T15:21:58.288,7566,0,0,0,0,10fb9be7d6ea,000086ee80c8 - 10fb9be7d6ea
805954,NaN,4,15,57,16,Declined by Candidate\n\nInterview\n\nStart,Candidate Withdrew,Provide Interview Rating and Comments,Provide Interview Rating and Comments,2024-11-04T15:21:58.288,6746,0,0,0,0,10fb9be7d6ea,000086ee80c8 - 10fb9be7d6ea
805953,NaN,4,15,57,16,Declined by Candidate\n\nInterview\n\nStart,Candidate Withdrew,Schedule Interview,Schedule Interview,2024-10-24T15:46:07.852,6746,0,0,0,0,10fb9be7d6ea,000086ee80c8 - 10fb9be7d6ea

In [23]:
df["Step"].value_counts().reset_index()["Step"].tolist()

['Review Decision',
 'Start',
 'Manager Screen',
 'Screen',
 'Schedule Interview',
 'Provide Interview Rating and Comments',
 'Make Interview Decision',
 'Assess Candidate',
 'Make Assessment Decision',
 'Assessment',
 'Integration: INT072a HireVue Assessment Assignment',
 'Service: Fire Integration',
 'Recruiter Interview',
 'Review Documents',
 'Change Personal Information',
 'Review Offer Letter',
 'Review Candidate',
 'Manager Interview',
 'Complete Questionnaire',
 'Consolidated Approval by Initiator',
 'Propose Compensation Offer/Employment Agreement',
 'Request One-Time Payment Offer/Employment Agreement',
 'Make Offer Decision',
 'Recruiter Screen',
 'Offer',
 'Consolidated Approval by HR Manager',
 'Consolidated Approval by Compensation Partner',
 'Candidate Experience Survey',
 'Ready for Hire - Send Hiring Manager Survey',
 'Recruiting Process Survey',
 'Do Not Move Forward',
 'Move Forward',
 'Recruiter Interview (30 min)',
 'Make Background Check Decision',
 'BGC / Examenes Preocupacionales',
 'Set Background Check Status',
 'Enter Govt or National IDs',
 'Ready for Hire – Do not send Manager Survey',
 'Enter Personal Information',
 'Additional Interview',
 'Confirm no manager survey to be sent',
 'LATAM Standard Questionnaire (2024)',
 'Workday Interview',
 'Colombia Standard Questionnaire (2024)',
 'Automatically Unpost Jobs',
 'Consolidated Approval by HR Executive or HR Executive (Local)',
 'Consolidated Approval by Global Compensation Executive',
 'Hiring Manager Interview (30 min)',
 'EEI Test',
 'Screening Decision',
 'Renegotiate Offer',
 'Additional Offer Packet Document(s)',
 'Screen Candidate',
 'Hiring Manager Interview (45 min)',
 'Additional Assessment',
 'Field Screening Test',
 'Hiring Manager Interview (60 min)',
 'Not Interested',
 'Review Company and Office Guides',
 'Recruiter Interview (45 min)',
 'Interested',
 'HM’s Manager Interview (30 min)',
 'Consolidated Approval by Global Compensation Manager',
 'HM’s Manager Interview (45 min)',
 'Additional Background / Reference Check',
 'Confirm no manager/additional hiring manager survey to be sent',
 'On Hold',
 'Backup',
 'Interview',
 'HM’s Manager Interview (60 min)',
 'Recruiter Interview (60 min)',
 'To Do: Update Job Posting Title as needed',
 'Integration: INT0x1-FurstPerson-ReqID-Outbound',
 'Change Government Identifiers',
 'Physical Abilities Test (PAT)']

In [24]:
df['Candidate_id'] = df['Case_id'].str.extract(r'^(.*?)\s*-')

df = df[df["Completed On"]>="2021-01-01"]
grouping_cols = ['Job_Requisition_Code', 'Candidate_id', 'Recruiting Agency', 'Region', 'Country', 'Job Family',
       'Job Family Group','Case_id', 'CW', 'Evergreen', 'Rejected', 'hired','Completed By',"Step", "Disposition Reason","All Stages for Candidate Current and Completed"]

In [25]:
df.sort_values(["Case_id", "Completed On"], inplace = True)

In [26]:
df.loc[df['Step'].isna() & (df['All Stages for Candidate Current and Completed'] == 'Start'), 'Step'] = 'Start'

In [27]:
df = df.melt(id_vars = grouping_cols, value_vars = ["Completed On"], var_name = "Type", value_name = "Value")
df.drop("Type", axis = 1, inplace = True)
df.rename(columns = {"Value":"timestamp"}, inplace = True)
df["timestamp"] = pd.to_datetime(df["timestamp"])

In [28]:
df[(df["timestamp"].dt.year == 2026) & (df["hired"]==1)]["Step"].value_counts()

Step
Review Documents                                                 292
Review Offer Letter                                              196
Complete Questionnaire                                           194
Make Offer Decision                                              149
Offer                                                            135
Consolidated Approval by Initiator                               134
Recruiting Process Survey                                        129
Make Interview Decision                                          129
Request One-Time Payment Offer/Employment Agreement              128
Propose Compensation Offer/Employment Agreement                  128
Candidate Experience Survey                                      125
Provide Interview Rating and Comments                            124
Ready for Hire - Send Hiring Manager Survey                      114
Make Background Check Decision                                   108
BGC / Examenes Preocupacionales                                  108
Schedule Interview                                               100
Set Background Check Status                                       91
Enter Govt or National IDs                                        84
Review Decision                                                   82
Start                                                             82
Consolidated Approval by Compensation Partner                     76
Consolidated Approval by HR Manager                               75
Change Personal Information                                       59
Ready for Hire – Do not send Manager Survey                       58
LATAM Standard Questionnaire (2024)                               57
Recruiter Interview                                               43
Colombia Standard Questionnaire (2024)                            43
Enter Personal Information                                        42
Confirm no manager survey to be sent                              40
Recruiter Interview (30 min)                                      31
Additional Interview                                              21
Recruiter Screen                                                  19
Screen                                                            18
Workday Interview                                                 14
Automatically Unpost Jobs                                         12
Renegotiate Offer                                                 12
Hiring Manager Interview (45 min)                                 11
Hiring Manager Interview (30 min)                                  6
Make Assessment Decision                                           6
Assessment                                                         6
Assess Candidate                                                   5
Manager Screen                                                     4
Consolidated Approval by HR Executive or HR Executive (Local)      3
Integration: INT072a HireVue Assessment Assignment                 3
Consolidated Approval by Global Compensation Executive             3
Service: Fire Integration                                          3
Review Company and Office Guides                                   2
HM’s Manager Interview (45 min)                                    2
HM’s Manager Interview (60 min)                                    1
Move Forward                                                       1
Name: count, dtype: int64

In [ ]:
import pm4py as pm

In [31]:
df.columns

Index(['Job_Requisition_Code', 'Candidate_id', 'Recruiting Agency', 'Region',
       'Country', 'Job Family', 'Job Family Group', 'Case_id', 'CW',
       'Evergreen', 'Rejected', 'hired', 'Completed By', 'Step',
       'Disposition Reason', 'All Stages for Candidate Current and Completed',
       'timestamp'],
      dtype='object')

In [32]:
df.head()

,Job_Requisition_Code,Candidate_id,Recruiting Agency,Region,Country,Job Family,Job Family Group,Case_id,CW,Evergreen,Rejected,hired,Completed By,Step,Disposition Reason,All Stages for Candidate Current and Completed,timestamp
0,10fb9be7d6ea,000086ee80c8,NaN,4,15,57,16,000086ee80c8 - 10fb9be7d6ea,0,0,0,0,6746,Review Decision,Candidate Withdrew,Declined by Candidate\n\nInterview\n\nStart,2024-10-17 15:21:25.626
1,10fb9be7d6ea,000086ee80c8,NaN,4,15,57,16,000086ee80c8 - 10fb9be7d6ea,0,0,0,0,7566,Start,Candidate Withdrew,Declined by Candidate\n\nInterview\n\nStart,2024-10-17 15:21:25.626
2,10fb9be7d6ea,000086ee80c8,NaN,4,15,57,16,000086ee80c8 - 10fb9be7d6ea,0,0,0,0,6746,Schedule Interview,Candidate Withdrew,Declined by Candidate\n\nInterview\n\nStart,2024-10-17 15:22:10.434
3,10fb9be7d6ea,000086ee80c8,NaN,4,15,57,16,000086ee80c8 - 10fb9be7d6ea,0,0,0,0,6746,Make Interview Decision,Candidate Withdrew,Declined by Candidate\n\nInterview\n\nStart,2024-10-17 15:22:10.434
4,10fb9be7d6ea,000086ee80c8,NaN,4,15,57,16,000086ee80c8 - 10fb9be7d6ea,0,0,0,0,7566,Recruiter Interview,Candidate Withdrew,Declined by Candidate\n\nInterview\n\nStart,2024-10-17 15:22:10.434

In [33]:
event_log = pm.convert_to_event_log(df, case_id_key = "Case_id", timestamp_key = "timestamp", activity_key = "Step")

In [34]:
df.to_csv("data/event_log_consolidated.csv", index = False)